Changes needed by flang
This drops the "pure" attribute from two procedures that flang
objected to. I think these were inconsequential, but I'm not certain.
Here are the error messages. These should be investigated to see if
they are valid, and if not, to report to flang. Note that with these
changes Truchas compiles.

error: Semantic errors in /home/nnc/Codes/truchas/worktrees/flang-port/src/truchas/drivers/sim_event_queue_type.F90
/home/nnc/Codes/truchas/worktrees/flang-port/src/truchas/drivers/sim_event_queue_type.F90:251:18: error: Object in DEALLOCATE statement is not deallocatable
        deallocate(item)
                   ^^^^
/home/nnc/Codes/truchas/worktrees/flang-port/src/truchas/drivers/sim_event_queue_type.F90:251:18: because: 'item' has polymorphic component '%action' in a pure subprogram
        deallocate(item)
                   ^^^^
/home/nnc/Codes/truchas/worktrees/flang-port/src/truchas/drivers/sim_event_queue_type.F90:247:33: Declaration of 'item'
      type(list_item), pointer :: item
                                  ^^^^

error: Semantic errors in /home/nnc/Codes/truchas/worktrees/flang-port/src/truchas/solid_mechanics/sm_model_type.F90
/home/nnc/Codes/truchas/worktrees/flang-port/src/truchas/solid_mechanics/sm_model_type.F90:89:54: error: Object in DEALLOCATE statement is not deallocatable
      if (associated(this%matl_model)) deallocate(this%matl_model)
                                                       ^^^^^^^^^^
/home/nnc/Codes/truchas/worktrees/flang-port/src/truchas/solid_mechanics/sm_model_type.F90:89:54: because: 'matl_model' has polymorphic component '%lame1f%f' in a pure subprogram
      if (associated(this%matl_model)) deallocate(this%matl_model)
                                                       ^^^^^^^^^^
/home/nnc/Codes/truchas/worktrees/flang-port/src/truchas/solid_mechanics/sm_model_type.F90:34:41: Declaration of 'matl_model'
      type(sm_material_model), pointer :: matl_model => null()
                                          ^^^^^^^^^^